# Generated by Django 4.2.1 on 2023-05-13 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0003_alter_creator_creator_id_alter_question_qa_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='quiz_id',
            field=models.CharField(max_length=255),
        ),
    ]
