# Generated by Django 4.2.1 on 2023-05-13 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0004_alter_question_quiz_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='creator_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='variant',
            name='qa_id',
            field=models.CharField(max_length=255),
        ),
    ]
