# Generated by Django 4.2.1 on 2023-05-13 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0006_alter_variant_qa_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='qa_id',
            field=models.CharField(max_length=255),
        ),
    ]
