# Generated by Django 4.2.1 on 2023-05-14 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0009_alter_question_quiz_id_alter_quiz_creator_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='quiz_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizapp.quiz'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='creator_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizapp.creator'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='qa_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizapp.question'),
        ),
    ]
