# Generated by Django 4.1.7 on 2023-05-14 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0011_quizresult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizresult',
            name='id',
        ),
        migrations.RemoveField(
            model_name='quizresult',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='quizresult',
            name='student',
        ),
        migrations.AddField(
            model_name='quizresult',
            name='creator_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quizapp.creator'),
        ),
        migrations.AddField(
            model_name='quizresult',
            name='quiz_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quizapp.quiz'),
        ),
        migrations.AddField(
            model_name='quizresult',
            name='res_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='quizresult',
            name='student_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quizapp.student'),
        ),
    ]
