# Generated by Django 4.1.7 on 2023-05-14 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0013_remove_quizresult_creator_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(default='210103@stu.edu.kz', max_length=254),
        ),
    ]
