# Generated by Django 4.1.7 on 2023-05-15 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0015_alter_quizresult_res_id_alter_student_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizresult',
            name='timetaken',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
